# wrangler.toml
name = "wedding_site"
main = "src/index.js"
compatibility_date = "2025-10-07"
routes = [
    {pattern = "giang-ngan.com", custom_domain = true},
    {pattern = "www.giang-ngan.com", custom_domain = true}
]

[assets]
directory = "./public"